// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/db/ (interfaces: DB)
//
// Generated by this command:
//
//	mockgen ./internal/db/ DB
//

// Package mock_db is a generated GoMock package.
package mock_db

import (
	context "context"
	crypto "crypto"
	sql "database/sql"
	url "net/url"
	reflect "reflect"
	time "time"

	domain "github.com/sidereusnuntius/gowiki/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
	isgomock struct{}
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// ActorIdByInbox mocks base method.
func (m *MockDB) ActorIdByInbox(ctx context.Context, iri *url.URL) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActorIdByInbox", ctx, iri)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActorIdByInbox indicates an expected call of ActorIdByInbox.
func (mr *MockDBMockRecorder) ActorIdByInbox(ctx, iri any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActorIdByInbox", reflect.TypeOf((*MockDB)(nil).ActorIdByInbox), ctx, iri)
}

// ActorIdByOutbox mocks base method.
func (m *MockDB) ActorIdByOutbox(ctx context.Context, iri *url.URL) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActorIdByOutbox", ctx, iri)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActorIdByOutbox indicates an expected call of ActorIdByOutbox.
func (mr *MockDBMockRecorder) ActorIdByOutbox(ctx, iri any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActorIdByOutbox", reflect.TypeOf((*MockDB)(nil).ActorIdByOutbox), ctx, iri)
}

// AddOutbox mocks base method.
func (m *MockDB) AddOutbox(ctx context.Context, apType string, raw []byte, id, outbox *url.URL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOutbox", ctx, apType, raw, id, outbox)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOutbox indicates an expected call of AddOutbox.
func (mr *MockDBMockRecorder) AddOutbox(ctx, apType, raw, id, outbox any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOutbox", reflect.TypeOf((*MockDB)(nil).AddOutbox), ctx, apType, raw, id, outbox)
}

// CollectionContains mocks base method.
func (m *MockDB) CollectionContains(ctx context.Context, collection, id *url.URL) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectionContains", ctx, collection, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CollectionContains indicates an expected call of CollectionContains.
func (mr *MockDBMockRecorder) CollectionContains(ctx, collection, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectionContains", reflect.TypeOf((*MockDB)(nil).CollectionContains), ctx, collection, id)
}

// CreateApObject mocks base method.
func (m *MockDB) CreateApObject(ctx context.Context, obj domain.FedObj, fetched int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApObject", ctx, obj, fetched)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateApObject indicates an expected call of CreateApObject.
func (mr *MockDBMockRecorder) CreateApObject(ctx, obj, fetched any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApObject", reflect.TypeOf((*MockDB)(nil).CreateApObject), ctx, obj, fetched)
}

// CreateLocalArticle mocks base method.
func (m *MockDB) CreateLocalArticle(ctx context.Context, userId int64, article domain.ArticleFed, initialEdit domain.Revision) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLocalArticle", ctx, userId, article, initialEdit)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLocalArticle indicates an expected call of CreateLocalArticle.
func (mr *MockDBMockRecorder) CreateLocalArticle(ctx, userId, article, initialEdit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLocalArticle", reflect.TypeOf((*MockDB)(nil).CreateLocalArticle), ctx, userId, article, initialEdit)
}

// DeleteAp mocks base method.
func (m *MockDB) DeleteAp(ctx context.Context, id *url.URL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAp", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAp indicates an expected call of DeleteAp.
func (mr *MockDBMockRecorder) DeleteAp(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAp", reflect.TypeOf((*MockDB)(nil).DeleteAp), ctx, id)
}

// Exists mocks base method.
func (m *MockDB) Exists(ctx context.Context, id *url.URL) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockDBMockRecorder) Exists(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockDB)(nil).Exists), ctx, id)
}

// FileExists mocks base method.
func (m *MockDB) FileExists(ctx context.Context, hash string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileExists", ctx, hash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileExists indicates an expected call of FileExists.
func (mr *MockDBMockRecorder) FileExists(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileExists", reflect.TypeOf((*MockDB)(nil).FileExists), ctx, hash)
}

// Follow mocks base method.
func (m *MockDB) Follow(ctx context.Context, follow domain.Follow) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Follow", ctx, follow)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Follow indicates an expected call of Follow.
func (mr *MockDBMockRecorder) Follow(ctx, follow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Follow", reflect.TypeOf((*MockDB)(nil).Follow), ctx, follow)
}

// GetActorInbox mocks base method.
func (m *MockDB) GetActorInbox(ctx context.Context, actor *url.URL) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActorInbox", ctx, actor)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActorInbox indicates an expected call of GetActorInbox.
func (mr *MockDBMockRecorder) GetActorInbox(ctx, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActorInbox", reflect.TypeOf((*MockDB)(nil).GetActorInbox), ctx, actor)
}

// GetApObject mocks base method.
func (m *MockDB) GetApObject(ctx context.Context, iri *url.URL) (domain.FedObj, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApObject", ctx, iri)
	ret0, _ := ret[0].(domain.FedObj)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApObject indicates an expected call of GetApObject.
func (mr *MockDBMockRecorder) GetApObject(ctx, iri any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApObject", reflect.TypeOf((*MockDB)(nil).GetApObject), ctx, iri)
}

// GetArticle mocks base method.
func (m *MockDB) GetArticle(ctx context.Context, title string, host, author sql.NullString) (domain.ArticleFed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticle", ctx, title, host, author)
	ret0, _ := ret[0].(domain.ArticleFed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticle indicates an expected call of GetArticle.
func (mr *MockDBMockRecorder) GetArticle(ctx, title, host, author any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticle", reflect.TypeOf((*MockDB)(nil).GetArticle), ctx, title, host, author)
}

// GetArticleById mocks base method.
func (m *MockDB) GetArticleById(ctx context.Context, id int64) (domain.ArticleFed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticleById", ctx, id)
	ret0, _ := ret[0].(domain.ArticleFed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticleById indicates an expected call of GetArticleById.
func (mr *MockDBMockRecorder) GetArticleById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticleById", reflect.TypeOf((*MockDB)(nil).GetArticleById), ctx, id)
}

// GetAuthDataByEmail mocks base method.
func (m *MockDB) GetAuthDataByEmail(ctx context.Context, email string) (domain.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthDataByEmail", ctx, email)
	ret0, _ := ret[0].(domain.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthDataByEmail indicates an expected call of GetAuthDataByEmail.
func (mr *MockDBMockRecorder) GetAuthDataByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthDataByEmail", reflect.TypeOf((*MockDB)(nil).GetAuthDataByEmail), ctx, email)
}

// GetAuthDataByUsername mocks base method.
func (m *MockDB) GetAuthDataByUsername(ctx context.Context, username string) (domain.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthDataByUsername", ctx, username)
	ret0, _ := ret[0].(domain.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthDataByUsername indicates an expected call of GetAuthDataByUsername.
func (mr *MockDBMockRecorder) GetAuthDataByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthDataByUsername", reflect.TypeOf((*MockDB)(nil).GetAuthDataByUsername), ctx, username)
}

// GetCollectionActivities mocks base method.
func (m *MockDB) GetCollectionActivities(ctx context.Context, collectionIRI *url.URL, last int64) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollectionActivities", ctx, collectionIRI, last)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCollectionActivities indicates an expected call of GetCollectionActivities.
func (mr *MockDBMockRecorder) GetCollectionActivities(ctx, collectionIRI, last any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollectionActivities", reflect.TypeOf((*MockDB)(nil).GetCollectionActivities), ctx, collectionIRI, last)
}

// GetCollectionMemberIRIS mocks base method.
func (m *MockDB) GetCollectionMemberIRIS(ctx context.Context, collectionIRI *url.URL) ([]*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollectionMemberIRIS", ctx, collectionIRI)
	ret0, _ := ret[0].([]*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCollectionMemberIRIS indicates an expected call of GetCollectionMemberIRIS.
func (mr *MockDBMockRecorder) GetCollectionMemberIRIS(ctx, collectionIRI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollectionMemberIRIS", reflect.TypeOf((*MockDB)(nil).GetCollectionMemberIRIS), ctx, collectionIRI)
}

// GetCollectionPage mocks base method.
func (m *MockDB) GetCollectionPage(ctx context.Context, iri *url.URL, last int64) ([]*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollectionPage", ctx, iri, last)
	ret0, _ := ret[0].([]*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCollectionPage indicates an expected call of GetCollectionPage.
func (mr *MockDBMockRecorder) GetCollectionPage(ctx, iri, last any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollectionPage", reflect.TypeOf((*MockDB)(nil).GetCollectionPage), ctx, iri, last)
}

// GetCollectionStart mocks base method.
func (m *MockDB) GetCollectionStart(ctx context.Context, collectionIRI *url.URL) (int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollectionStart", ctx, collectionIRI)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCollectionStart indicates an expected call of GetCollectionStart.
func (mr *MockDBMockRecorder) GetCollectionStart(ctx, collectionIRI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollectionStart", reflect.TypeOf((*MockDB)(nil).GetCollectionStart), ctx, collectionIRI)
}

// GetCollectiveById mocks base method.
func (m *MockDB) GetCollectiveById(ctx context.Context, id int64) (domain.Collective, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollectiveById", ctx, id)
	ret0, _ := ret[0].(domain.Collective)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCollectiveById indicates an expected call of GetCollectiveById.
func (mr *MockDBMockRecorder) GetCollectiveById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollectiveById", reflect.TypeOf((*MockDB)(nil).GetCollectiveById), ctx, id)
}

// GetFile mocks base method.
func (m *MockDB) GetFile(ctx context.Context, hash string) (domain.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile", ctx, hash)
	ret0, _ := ret[0].(domain.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFile indicates an expected call of GetFile.
func (mr *MockDBMockRecorder) GetFile(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockDB)(nil).GetFile), ctx, hash)
}

// GetFollowers mocks base method.
func (m *MockDB) GetFollowers(ctx context.Context, id *url.URL) ([]*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowers", ctx, id)
	ret0, _ := ret[0].([]*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowers indicates an expected call of GetFollowers.
func (mr *MockDBMockRecorder) GetFollowers(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowers", reflect.TypeOf((*MockDB)(nil).GetFollowers), ctx, id)
}

// GetLastRevisionID mocks base method.
func (m *MockDB) GetLastRevisionID(ctx context.Context, title string) (int64, *url.URL, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastRevisionID", ctx, title)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(*url.URL)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetLastRevisionID indicates an expected call of GetLastRevisionID.
func (mr *MockDBMockRecorder) GetLastRevisionID(ctx, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastRevisionID", reflect.TypeOf((*MockDB)(nil).GetLastRevisionID), ctx, title)
}

// GetProfile mocks base method.
func (m *MockDB) GetProfile(ctx context.Context, username, hostname string) (domain.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx, username, hostname)
	ret0, _ := ret[0].(domain.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockDBMockRecorder) GetProfile(ctx, username, hostname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockDB)(nil).GetProfile), ctx, username, hostname)
}

// GetRevisionList mocks base method.
func (m *MockDB) GetRevisionList(ctx context.Context, title string) ([]domain.Revision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRevisionList", ctx, title)
	ret0, _ := ret[0].([]domain.Revision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRevisionList indicates an expected call of GetRevisionList.
func (mr *MockDBMockRecorder) GetRevisionList(ctx, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRevisionList", reflect.TypeOf((*MockDB)(nil).GetRevisionList), ctx, title)
}

// GetUser mocks base method.
func (m *MockDB) GetUser(ctx context.Context, username, hostname string) (domain.UserCore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, username, hostname)
	ret0, _ := ret[0].(domain.UserCore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockDBMockRecorder) GetUser(ctx, username, hostname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockDB)(nil).GetUser), ctx, username, hostname)
}

// GetUserApId mocks base method.
func (m *MockDB) GetUserApId(ctx context.Context, username string) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserApId", ctx, username)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserApId indicates an expected call of GetUserApId.
func (mr *MockDBMockRecorder) GetUserApId(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserApId", reflect.TypeOf((*MockDB)(nil).GetUserApId), ctx, username)
}

// GetUserByID mocks base method.
func (m *MockDB) GetUserByID(ctx context.Context, id int64) (domain.UserFed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(domain.UserFed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockDBMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockDB)(nil).GetUserByID), ctx, id)
}

// GetUserFed mocks base method.
func (m *MockDB) GetUserFed(ctx context.Context, id *url.URL) (domain.UserFed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserFed", ctx, id)
	ret0, _ := ret[0].(domain.UserFed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserFed indicates an expected call of GetUserFed.
func (mr *MockDBMockRecorder) GetUserFed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserFed", reflect.TypeOf((*MockDB)(nil).GetUserFed), ctx, id)
}

// GetUserPrivateKey mocks base method.
func (m *MockDB) GetUserPrivateKey(ctx context.Context, id int64) (*url.URL, crypto.PrivateKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPrivateKey", ctx, id)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(crypto.PrivateKey)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserPrivateKey indicates an expected call of GetUserPrivateKey.
func (mr *MockDBMockRecorder) GetUserPrivateKey(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPrivateKey", reflect.TypeOf((*MockDB)(nil).GetUserPrivateKey), ctx, id)
}

// GetUserPrivateKeyByURI mocks base method.
func (m *MockDB) GetUserPrivateKeyByURI(ctx context.Context, arg1 *url.URL) (crypto.PrivateKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPrivateKeyByURI", ctx, arg1)
	ret0, _ := ret[0].(crypto.PrivateKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPrivateKeyByURI indicates an expected call of GetUserPrivateKeyByURI.
func (mr *MockDBMockRecorder) GetUserPrivateKeyByURI(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPrivateKeyByURI", reflect.TypeOf((*MockDB)(nil).GetUserPrivateKeyByURI), ctx, arg1)
}

// GetUserURI mocks base method.
func (m *MockDB) GetUserURI(ctx context.Context, id int64) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserURI", ctx, id)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserURI indicates an expected call of GetUserURI.
func (mr *MockDBMockRecorder) GetUserURI(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserURI", reflect.TypeOf((*MockDB)(nil).GetUserURI), ctx, id)
}

// InsertOrUpdateUser mocks base method.
func (m *MockDB) InsertOrUpdateUser(ctx context.Context, u domain.UserFed, fetched time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrUpdateUser", ctx, u, fetched)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOrUpdateUser indicates an expected call of InsertOrUpdateUser.
func (mr *MockDBMockRecorder) InsertOrUpdateUser(ctx, u, fetched any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrUpdateUser", reflect.TypeOf((*MockDB)(nil).InsertOrUpdateUser), ctx, u, fetched)
}

// InsertUser mocks base method.
func (m *MockDB) InsertUser(ctx context.Context, user domain.UserFedInternal, account domain.Account, reason, invitation string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUser", ctx, user, account, reason, invitation)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertUser indicates an expected call of InsertUser.
func (mr *MockDBMockRecorder) InsertUser(ctx, user, account, reason, invitation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUser", reflect.TypeOf((*MockDB)(nil).InsertUser), ctx, user, account, reason, invitation)
}

// IsUserTrusted mocks base method.
func (m *MockDB) IsUserTrusted(ctx context.Context, id int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserTrusted", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserTrusted indicates an expected call of IsUserTrusted.
func (mr *MockDBMockRecorder) IsUserTrusted(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserTrusted", reflect.TypeOf((*MockDB)(nil).IsUserTrusted), ctx, id)
}

// OutboxForInbox mocks base method.
func (m *MockDB) OutboxForInbox(ctx context.Context, inboxIRI *url.URL) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutboxForInbox", ctx, inboxIRI)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OutboxForInbox indicates an expected call of OutboxForInbox.
func (mr *MockDBMockRecorder) OutboxForInbox(ctx, inboxIRI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutboxForInbox", reflect.TypeOf((*MockDB)(nil).OutboxForInbox), ctx, inboxIRI)
}

// PersistRemoteArticle mocks base method.
func (m *MockDB) PersistRemoteArticle(ctx context.Context, article domain.ArticleFed, articleRaw domain.FedObj) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PersistRemoteArticle", ctx, article, articleRaw)
	ret0, _ := ret[0].(error)
	return ret0
}

// PersistRemoteArticle indicates an expected call of PersistRemoteArticle.
func (mr *MockDBMockRecorder) PersistRemoteArticle(ctx, article, articleRaw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistRemoteArticle", reflect.TypeOf((*MockDB)(nil).PersistRemoteArticle), ctx, article, articleRaw)
}

// Save mocks base method.
func (m *MockDB) Save(ctx context.Context, file domain.File) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, file)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockDBMockRecorder) Save(ctx, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockDB)(nil).Save), ctx, file)
}

// UpdateAp mocks base method.
func (m *MockDB) UpdateAp(ctx context.Context, id *url.URL, rawJSON []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAp", ctx, id, rawJSON)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAp indicates an expected call of UpdateAp.
func (mr *MockDBMockRecorder) UpdateAp(ctx, id, rawJSON any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAp", reflect.TypeOf((*MockDB)(nil).UpdateAp), ctx, id, rawJSON)
}

// UpdateArticle mocks base method.
func (m *MockDB) UpdateArticle(ctx context.Context, prevId, articleId, userId int64, summary, newContent string, apId *url.URL) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateArticle", ctx, prevId, articleId, userId, summary, newContent, apId)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateArticle indicates an expected call of UpdateArticle.
func (mr *MockDBMockRecorder) UpdateArticle(ctx, prevId, articleId, userId, summary, newContent, apId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateArticle", reflect.TypeOf((*MockDB)(nil).UpdateArticle), ctx, prevId, articleId, userId, summary, newContent, apId)
}

// UserExists mocks base method.
func (m *MockDB) UserExists(ctx context.Context, id *url.URL) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserExists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserExists indicates an expected call of UserExists.
func (mr *MockDBMockRecorder) UserExists(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserExists", reflect.TypeOf((*MockDB)(nil).UserExists), ctx, id)
}
