// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
)

type Account struct {
	ID            int64
	Password      string
	Admin         bool
	Email         string
	EmailVerified bool
	Approved      bool
	UserID        int64
	Created       string
	LastUpdated   string
}

type ApprovalRequest struct {
	ID        int64
	AccountID int64
	Reason    string
	Approved  sql.NullBool
	Reviewer  sql.NullInt64
	Created   string
}

type Article struct {
	ID          int64
	Local       bool
	ApID        string
	Url         sql.NullString
	InstanceID  sql.NullInt64
	Language    string
	MediaType   string
	Title       string
	Protected   bool
	Summary     sql.NullString
	Content     string
	Created     int64
	LastUpdated int64
	LastFetched sql.NullInt64
}

type Invitation struct {
	ID      string
	Used    bool
	UsedBy  sql.NullInt64
	UsedAt  sql.NullString
	MadeBy  int64
	Created string
}

type Revision struct {
	ID         int64
	ApID       sql.NullString
	ArticleID  int64
	UserID     int64
	Summary    sql.NullString
	Diff       string
	Reviewed   bool
	Reviewer   sql.NullInt64
	ReviewedAt sql.NullString
	Published  bool
	Prev       sql.NullInt64
	BasedOn    sql.NullInt64
	Created    int64
}

type User struct {
	ID          int64
	Bot         bool
	Local       bool
	ApID        string
	Url         sql.NullString
	Username    string
	Name        string
	Domain      sql.NullString
	Summary     sql.NullString
	Inbox       string
	Outbox      string
	Followers   string
	PublicKey   string
	PrivateKey  string
	Trusted     bool
	Created     string
	LastUpdated string
	LastFetched sql.NullString
}
