// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
)

type Account struct {
	ID            int64
	Password      string
	Admin         bool
	Email         string
	EmailVerified bool
	Approved      bool
	UserID        int64
	Created       string
	LastUpdated   string
}

type ApprovalRequest struct {
	ID        int64
	AccountID int64
	Reason    string
	Approved  sql.NullBool
	Reviewer  sql.NullInt64
	CreatedAt string
}

type Invitation struct {
	ID        string
	Used      bool
	UsedBy    sql.NullInt64
	UsedAt    sql.NullString
	MadeBy    int64
	CreatedAt string
}

type User struct {
	ID          int64
	Bot         bool
	Local       bool
	ApID        string
	Username    string
	Name        string
	Domain      sql.NullString
	Summary     sql.NullString
	Inbox       string
	Outbox      string
	Followers   string
	PublicKey   string
	PrivateKey  string
	Created     string
	LastUpdated string
	LastFetched sql.NullString
}
