// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"
	"database/sql"
)

const authUserByEmail = `-- name: AuthUserByEmail :one
SELECT
    u.id AS user_id,
    a.id AS account_id,
    u.username,
    a.password,
    a.admin
FROM users AS u
JOIN accounts AS a
ON a.user_id = u.id
WHERE u.local AND a.email = ?1
LIMIT 1
`

type AuthUserByEmailRow struct {
	UserID    int64
	AccountID int64
	Username  string
	Password  string
	Admin     bool
}

func (q *Queries) AuthUserByEmail(ctx context.Context, email string) (AuthUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, authUserByEmail, email)
	var i AuthUserByEmailRow
	err := row.Scan(
		&i.UserID,
		&i.AccountID,
		&i.Username,
		&i.Password,
		&i.Admin,
	)
	return i, err
}

const authUserByUsername = `-- name: AuthUserByUsername :one
SELECT
    u.id AS user_id,
    a.id AS account_id,
    u.username,
    a.password,
    a.admin
FROM users AS u
JOIN accounts AS a
ON a.user_id = u.id
WHERE u.local AND u.username = ?1
LIMIT 1
`

type AuthUserByUsernameRow struct {
	UserID    int64
	AccountID int64
	Username  string
	Password  string
	Admin     bool
}

func (q *Queries) AuthUserByUsername(ctx context.Context, username string) (AuthUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, authUserByUsername, username)
	var i AuthUserByUsernameRow
	err := row.Scan(
		&i.UserID,
		&i.AccountID,
		&i.Username,
		&i.Password,
		&i.Admin,
	)
	return i, err
}

const createAccount = `-- name: CreateAccount :exec
INSERT INTO 
    accounts (password, admin, email, user_id, created, last_updated)
VALUES 
    (?, ?, ?, ?, ?, ?)
`

type CreateAccountParams struct {
	Password    string
	Admin       bool
	Email       string
	UserID      int64
	Created     string
	LastUpdated string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.ExecContext(ctx, createAccount,
		arg.Password,
		arg.Admin,
		arg.Email,
		arg.UserID,
		arg.Created,
		arg.LastUpdated,
	)
	return err
}

const createLocalUser = `-- name: CreateLocalUser :one
INSERT INTO users (
    ap_id,
    username,
    name,
    summary,
    inbox,
    outbox,
    followers,
    public_key,
    private_key,
    created,
    last_updated
    )
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11) RETURNING id
`

type CreateLocalUserParams struct {
	ApID        string
	Username    string
	Name        string
	Summary     sql.NullString
	Inbox       string
	Outbox      string
	Followers   string
	PublicKey   string
	PrivateKey  string
	Created     string
	LastUpdated string
}

func (q *Queries) CreateLocalUser(ctx context.Context, arg CreateLocalUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createLocalUser,
		arg.ApID,
		arg.Username,
		arg.Name,
		arg.Summary,
		arg.Inbox,
		arg.Outbox,
		arg.Followers,
		arg.PublicKey,
		arg.PrivateKey,
		arg.Created,
		arg.LastUpdated,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
