ALTER TABLE instances ADD COLUMN outbox VARCHAR(255);
ALTER TABLE instances ADD COLUMN followers VARCHAR(255);
ALTER TABLE instances ADD COLUMN url VARCHAR(255);
ALTER TABLE instances ADD COLUMN blocked BOOLEAN DEFAULT FALSE NOT NULL;