ALTER TABLE instances DROP COLUMN blocked BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE instances DROP COLUMN url VARCHAR(255);
ALTER TABLE instances DROP COLUMN followers VARCHAR(255);
ALTER TABLE instances DROP COLUMN outbox VARCHAR(255);