// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
)

type Account struct {
	ID            int64
	Password      string
	Admin         bool
	Email         string
	EmailVerified bool
	Approved      bool
	UserID        int64
	Created       string
	LastUpdated   string
}

type ApCollectionMember struct {
	ID             int64
	CollectionApID string
	MemberApID     string
	InsertedAt     int64
}

type ApObjectCache struct {
	ID          int64
	ApID        string
	LocalTable  sql.NullString
	LocalID     sql.NullInt64
	Type        string
	RawJson     []byte
	InsertedAt  int64
	LastUpdated sql.NullInt64
	LastFetched sql.NullInt64
}

type ApprovalRequest struct {
	ID        int64
	AccountID int64
	Reason    string
	Approved  sql.NullBool
	Reviewer  sql.NullInt64
	Created   string
}

type Article struct {
	ID           int64
	Local        bool
	ApID         string
	Author       sql.NullString
	AttributedTo sql.NullString
	Url          sql.NullString
	Language     string
	MediaType    string
	Title        string
	Host         sql.NullString
	Type         string
	Protected    bool
	Summary      sql.NullString
	Content      string
	Published    sql.NullInt64
	InsertedAt   int64
	LastUpdated  int64
	LastFetched  sql.NullInt64
}

type ArticleFile struct {
	ArticleID int64
	FileID    int64
}

type Collective struct {
	ID         int64
	Name       sql.NullString
	Host       string
	Url        sql.NullString
	PublicKey  sql.NullString
	PrivateKey sql.NullString
	Inbox      sql.NullString
	Outbox     sql.NullString
	Followers  sql.NullString
	Blocked    bool
	Created    int64
	Updated    int64
}

type File struct {
	ID         int64
	Digest     string
	Path       sql.NullString
	ApID       string
	Name       sql.NullString
	Host       sql.NullString
	Filename   sql.NullString
	Type       string
	MimeType   string
	SizeBytes  sql.NullInt64
	Local      bool
	UploadedBy sql.NullInt64
	Url        string
	Created    int64
}

type Follow struct {
	ID               int64
	FollowApID       string
	FollowerApID     string
	FolloweeApID     string
	FollowerInboxUrl sql.NullString
	Approved         bool
	CreatedAt        sql.NullInt64
}

type Invitation struct {
	ID      string
	Used    bool
	UsedBy  sql.NullInt64
	UsedAt  sql.NullString
	MadeBy  int64
	Created string
}

type Revision struct {
	ID         int64
	ApID       sql.NullString
	ArticleID  int64
	UserID     sql.NullInt64
	Summary    sql.NullString
	Diff       string
	Reviewed   bool
	Reviewer   sql.NullInt64
	ReviewedAt sql.NullString
	Published  bool
	Prev       sql.NullInt64
	BasedOn    sql.NullInt64
	Created    int64
}

type User struct {
	ID          int64
	Bot         bool
	Local       bool
	ApID        string
	Url         sql.NullString
	Username    sql.NullString
	Name        sql.NullString
	Host        sql.NullString
	InstanceID  sql.NullInt64
	Summary     sql.NullString
	Inbox       string
	Outbox      string
	Followers   string
	PublicKey   string
	PrivateKey  string
	Trusted     bool
	Created     int64
	LastUpdated int64
	LastFetched sql.NullInt64
}
